// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkb-HbYSAqkVS_G2tOiiUpRFi4RhE2_Rk',
    appId: '1:787625185970:web:f22380f87edf4d0386efab',
    messagingSenderId: '787625185970',
    projectId: 'animeapp-27fc4',
    authDomain: 'animeapp-27fc4.firebaseapp.com',
    storageBucket: 'animeapp-27fc4.appspot.com',
    measurementId: 'G-5C1V419Y1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFQKgBthePaFtntY6b0-1OKx8F59qP7CM',
    appId: '1:787625185970:android:fe028e73101628b286efab',
    messagingSenderId: '787625185970',
    projectId: 'animeapp-27fc4',
    storageBucket: 'animeapp-27fc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCRH4kASIrPP-GGQIY9E6F5rZolFhUeTQ',
    appId: '1:787625185970:ios:9a1c35e1b93273c586efab',
    messagingSenderId: '787625185970',
    projectId: 'animeapp-27fc4',
    storageBucket: 'animeapp-27fc4.appspot.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCRH4kASIrPP-GGQIY9E6F5rZolFhUeTQ',
    appId: '1:787625185970:ios:2b1908e30d6d907a86efab',
    messagingSenderId: '787625185970',
    projectId: 'animeapp-27fc4',
    storageBucket: 'animeapp-27fc4.appspot.com',
    iosBundleId: 'com.example.animeApp.RunnerTests',
  );
}
